/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.iambenkay.kuda

import kotlin.test.Test
import kotlin.test.assertTrue

class KudaTest {
    @Test fun testSomeLibraryMethod() {
//        val classUnderTest = Kuda()
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
